#!/bin/bash

echo "bird
hund
kat
elefant" | $2/hfst-strings2fst -j -f $1 > NounRoots

echo "bon
long
jun
alt
grav" | $2/hfst-strings2fst -j -f $1 > AdjRoots

echo '[(g e)]' | $2/hfst-regexp2fst -f $1 > NounPrefix

echo '[ ([m a l] | [n e]) ]' | $2/hfst-regexp2fst -f $1 > AdjPrefixes

echo '[o]' | $2/hfst-regexp2fst -f $1 -j > Nend

echo '[a]' | $2/hfst-regexp2fst -f $1 -j > Adjend

echo '[(j)]' | $2/hfst-regexp2fst -f $1 -j > Number

echo '[(n)]' | $2/hfst-regexp2fst -f $1 -j > Case

echo '[ ([i n] | [e t] | [e g])* [@"Nend" | @"Adjend"] ]' | \
     $2/hfst-regexp2fst -f $1 > Nmf

echo '([e g] | [e t])* [@"Adjend" | [e c @"Nend"]]' | \
     $2/hfst-regexp2fst -f $1 > Adj

$2/hfst-concatenate NounPrefix NounRoots | $2/hfst-concatenate -2 Nmf > NounStem
$2/hfst-concatenate AdjPrefixes AdjRoots | $2/hfst-concatenate -2 Adj > AdjectiveStem
$2/hfst-disjunct NounStem AdjectiveStem > Stems
$2/hfst-concatenate Number Case | $2/hfst-concatenate -1 Stems > Result

$2/hfst-minimize Result > TMP
mv TMP Result

rm -f Adj NounStem AdjRoots Adjend Number Stems NounPrefix
rm -f AdjPrefixes NounRoots Case Nmf Nend AdjectiveStem
