#!/bin/bash

echo 'bird
hund
kat
elefant' | $2/hfst-strings2fst -j -f $1 > Nouns

echo '[ [i n] | [e t] | [e g] ]*'| $2/hfst-regexp2fst -f $1 > Nmf

echo '[o]' | $2/hfst-regexp2fst -f $1 > Nend

echo '[(j)]' | $2/hfst-regexp2fst -f $1 > Number

echo '[(n)]' | $2/hfst-regexp2fst -f $1 > Case

echo '[0]' | $2/hfst-regexp2fst -f $1 > Result
for i in Nouns Nmf Nend Number Case;
do
  $2/hfst-concatenate Result $i > TMP;
  mv TMP Result;
done

$2/hfst-minimize Result > TMP
mv TMP Result

rm -f Number Nouns Case Nmf Nend
